import React, { useRef, useEffect, useLayoutEffect } from 'react'
import Head from 'next/head'
import { FirstSection } from '@/sections/home/FirstSection'
import { SecondSection } from '@/sections/home/About'
import { ThirdSection } from '@/sections/home/Next'
import Case from '@/sections/home/Case'
import Jobs from '@/sections/home/Jobs'
import { gsap } from 'gsap'
import { ScrollSmoother } from 'gsap-trial/dist/ScrollSmoother'
import { Contact } from '@/sections/home/Contact'
import YellowDot from '@/components/YellowDot'
import { useLocomotiveScroll } from 'react-locomotive-scroll'
import SmoothScroll from '@/components/SmoothScroll/SmoothScroll'



export default function Home() {

  const el = useRef();






  return (<>

    <div ref={el}>
      <SmoothScroll>
        <Head>
          <title>{`<EduStadler/>`}</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <FirstSection
          overTitle="Interactive programmer"
          name="Edu Stadler"
        />
        <SecondSection
          overTitle="About"
          name=""
          subtitle="I am a Brazilian developer with a passion for front-end development and user interactions since 2017. Throughout my journey, I have focused on enhancing my skills in JavaScript and continuously worked on improving my WordPress full-stack capabilities. Alongside my technical pursuits, I have explored my creative side, delving into the world of generative art using JavaScript and p5.js. This unique blend of technical expertise and artistic flair defines me as a dedicated and innovative professional."
        />
        <ThirdSection
          name="Technologies"
        />
        <Case />
        {/* <Jobs /> */}
        <Contact/>
        <YellowDot/>
      </SmoothScroll>
    </div>
  </>);
}
