import Head from 'next/head'
import { FirstSection } from '@/sections/home/FirstSection'
import { SecondSection } from '@/sections/home/About'
import { ThirdSection } from '@/sections/home/Next'
import { Wordpress } from '@/sections/home/Wordpress'
import Case from '@/sections/home/Case'
import Jobs from '@/sections/home/Jobs'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* FIRST SECTION */}

      <FirstSection
        overTitle="Hey, I'm"
        name="Edu Stadler"
        subtitle="My new brand portfolio to 2023, focused in front-end, react and wordpress." />

      {/* ABOUT */}

      <SecondSection
        overTitle="About"
        name=""
        subtitle="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ipsum magna, ornare vel finibus sit amet, porta id est.
        Donec ante arcu, blandit id nunc sed, porttitor tempus nibh. Fusce ornare sem non commodo scelerisque. Maecenas tincidunt elit eros,
        quis fermentum arcu posuere ut. Proin et tincidunt ipsum."
      />

      {/* NEXT.JS */}

      <ThirdSection
        overTitle="Technologies"
        name="Taking controls of new updates"
        subtitle="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ipsum magna, ornare vel finibus sit amet, porta id est.
        Donec ante arcu, blandit id nunc sed, porttitor tempus nibh. Fusce ornare sem non commodo scelerisque. Maecenas tincidunt elit eros,
        quis fermentum arcu posuere ut. Proin et tincidunt ipsum."/>



      {/* CASE */}
      <Case />

      {/* Some clients */}

      <Jobs/>

      {/* CONTACT */}

      <SecondSection
        overTitle="What's up!"
        name="Contact" />
    </>
  )
}
